allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
  vue3-snackbar: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - vue3-snackbar
